### test
GET http://:8080/index.html


### test
POST http://:8080/test.html
Content-Type: application/json

{"a":1}

### test
POST http://:8080/test.cgi
Content-Type: application/json

{"a":1}

### test
POST http://:8080/python.cgi
Content-Type: application/json

{"a":1}